// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBamLmX9-47LGmG6Iz4mUZwAFUixAl7ahE',
    appId: '1:1050093380174:web:3593ac8e3089c04ec1991f',
    messagingSenderId: '1050093380174',
    projectId: 'mobileprogramming-58f28',
    authDomain: 'mobileprogramming-58f28.firebaseapp.com',
    storageBucket: 'mobileprogramming-58f28.firebasestorage.app',
    measurementId: 'G-7MV811WKJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGkCKyD0PD_XEUJZAF03lkbi0FI7Ao12M',
    appId: '1:1050093380174:android:9946285493438ba6c1991f',
    messagingSenderId: '1050093380174',
    projectId: 'mobileprogramming-58f28',
    storageBucket: 'mobileprogramming-58f28.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBamLmX9-47LGmG6Iz4mUZwAFUixAl7ahE',
    appId: '1:1050093380174:web:ea54c6adfe523f6ec1991f',
    messagingSenderId: '1050093380174',
    projectId: 'mobileprogramming-58f28',
    authDomain: 'mobileprogramming-58f28.firebaseapp.com',
    storageBucket: 'mobileprogramming-58f28.firebasestorage.app',
    measurementId: 'G-WR8504XS2N',
  );
}
